// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCoreEfSamples.Context;

namespace NetCoreEfSamples.Migrations
{
    [DbContext(typeof(GenericSampleCtx))]
    [Migration("20201013103719_Sample_GenericSample")]
    partial class Sample_GenericSample
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NetCoreEfSamples.Models.GenericBaseModel.GenericPropChild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PropBaseValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropChildValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("genericPropChildren");
                });

            modelBuilder.Entity("NetCoreEfSamples.Models.GenericBaseModel.MainSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnyVal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NavPropId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NavPropId");

                    b.ToTable("mainSamples");
                });

            modelBuilder.Entity("NetCoreEfSamples.Models.GenericBaseModel.MainSample", b =>
                {
                    b.HasOne("NetCoreEfSamples.Models.GenericBaseModel.GenericPropChild", "NavProp")
                        .WithMany()
                        .HasForeignKey("NavPropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
